# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Paso para hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso para configurar el JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Paso para instalar el SDK de Android 35
      - name: Install Android SDK 35
        run: |
          sudo apt update
          sudo apt install -y android-sdk
          sdkmanager "platforms;android-35" "build-tools;30.0.3" "tools" "platform-tools"

      # Paso para configurar el Android SDK
      - name: Configure Android SDK
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH

      # Paso para configurar Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Paso para construir el proyecto
      - name: Build with Gradle
        run: ./gradlew build

      # Paso para correr el análisis de seguridad con CodeQL (si lo tienes configurado)
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
